version: "3.9"
   
services:
  db:
    build:
      context: ./docker-db
      dockerfile: Dockerfile-db
    networks:
      - spear_network
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    command: [ "/app/backendserver" ]
    ports:
      - "8000:8000"
    networks:
      - spear_network
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy
networks:
  spear_network:
    driver: bridge
