CREATE TABLE notifications(
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
	title CHARACTER(70) NOT NULL,
	body TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id)
  );
